# Generated by Django 2.0.10 on 2019-01-11 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaperlessVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='文件名')),
                ('type', models.IntegerField(choices=[(6, '标准宁波经信委版'), (3, '政协宁波版'), (4, '人大温州平阳版'), (9, '履职宁波政协版'), (7, '标准宁波市场监管局版'), (8, '履职宁波人大版'), (5, '政协舟山版'), (1, '人大宁波市版'), (2, '人大宁波辖区版')], default=1, verbose_name='版本类型')),
                ('file_path', models.FileField(upload_to='media', verbose_name='上传文件')),
                ('md5', models.CharField(blank=True, max_length=100, null=True, verbose_name='文件MD5')),
                ('content', models.TextField(max_length=500, verbose_name='版本更新功能')),
                ('version', models.CharField(max_length=100, verbose_name='版本号')),
                ('test_report', models.FileField(upload_to='report', verbose_name='测试报告')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='img', verbose_name='二维码')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('datetime_modified', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '无纸化版本',
                'verbose_name_plural': '无纸化版本',
            },
        ),
    ]
