# Generated by Django 2.0.10 on 2019-01-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='版本')),
                ('version_code', models.CharField(max_length=20, verbose_name='版本号')),
                ('content', models.CharField(max_length=200, verbose_name='版本更迭新增流程')),
                ('file', models.FileField(upload_to='test_process', verbose_name='流程文件')),
            ],
            options={
                'verbose_name': '无纸化版本',
                'verbose_name_plural': '无纸化版本',
            },
        ),
        migrations.AlterField(
            model_name='paperlessversion',
            name='test_report',
            field=models.FileField(blank=True, null=True, upload_to='report', verbose_name='测试报告'),
        ),
        migrations.AlterField(
            model_name='paperlessversion',
            name='type',
            field=models.IntegerField(choices=[(4, '人大温州平阳版'), (8, '履职宁波人大版'), (9, '履职宁波政协版'), (2, '人大宁波辖区版'), (1, '人大宁波市版'), (5, '政协舟山版'), (7, '标准宁波市场监管局版'), (3, '政协宁波版'), (6, '标准宁波经信委版')], default=1, verbose_name='版本类型'),
        ),
    ]
