# Generated by Django 2.0.10 on 2019-01-19 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version', '0002_auto_20190112_1840'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paperlessversion',
            options={'permissions': (('view_ad_campaing', 'view_ad_campaing'),), 'verbose_name': '无纸化版本', 'verbose_name_plural': '无纸化版本'},
        ),
        migrations.AlterField(
            model_name='paperlessversion',
            name='type',
            field=models.IntegerField(choices=[(3, '政协宁波版'), (5, '政协舟山版'), (10, '舟山市委'), (1, '人大宁波市版'), (6, '标准宁波经信委版'), (4, '人大温州平阳版'), (9, '履职宁波政协版'), (7, '标准宁波市场监管局版'), (2, '人大宁波辖区版'), (8, '履职宁波人大版')], default=1, verbose_name='版本类型'),
        ),
    ]
