# Generated by Django 2.0.10 on 2019-02-20 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version', '0003_auto_20190119_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paperlessversion',
            name='type',
            field=models.IntegerField(choices=[(6, '标准宁波经信委版'), (10, '舟山市委'), (3, '政协宁波版'), (8, '履职宁波人大版'), (4, '人大温州平阳版'), (11, '智慧人大'), (5, '政协舟山版'), (9, '履职宁波政协版'), (2, '人大宁波辖区版'), (7, '标准宁波市场监管局版'), (1, '人大宁波市版')], default=1, verbose_name='版本类型'),
        ),
    ]
