# Generated by Django 2.0.10 on 2019-02-20 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version', '0004_auto_20190220_0933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testprocess',
            options={'verbose_name': '测试流程', 'verbose_name_plural': '测试流程'},
        ),
        migrations.AddField(
            model_name='testprocess',
            name='type',
            field=models.IntegerField(choices=[(3, '市辖区人大无纸化测试流程'), (4, '舟山人大无纸化测试流程'), (6, '智慧人大测试流程'), (5, '舟山市府无纸化测试流程'), (1, '市人大无纸化测试流程'), (2, '市政协无纸化测试流程')], default=1, verbose_name='版本类型'),
        ),
        migrations.AlterField(
            model_name='paperlessversion',
            name='type',
            field=models.IntegerField(choices=[(3, '政协宁波版'), (6, '标准宁波经信委版'), (7, '标准宁波市场监管局版'), (9, '履职宁波政协版'), (1, '人大宁波市版'), (5, '政协舟山版'), (10, '舟山市委'), (11, '智慧人大'), (4, '人大温州平阳版'), (8, '履职宁波人大版'), (2, '人大宁波辖区版')], default=1, verbose_name='版本类型'),
        ),
    ]
